name: OpenMinetopia
version: '1.3.0'
main: nl.openminetopia.OpenMinetopia
api-version: '1.21'
loader: nl.openminetopia.OpenMinetopiaLoader
authors: [ 'KaasPlakje', 'OmeJan', 'TheBathDuck', 'NijhuisSven' ]
dependencies:
  server:
    PlaceholderAPI:
      load: BEFORE
      required: false
    WorldEdit:
      load: BEFORE
      required: true
    WorldGuard:
      load: BEFORE
      required: true
    Vault:
      required: false
